### ISSUE TITLE
Missing paginator on optimized builds

### ISSUE THREAD

**Issue by Neraste** [Nadeflore/dakara-client-web#22] opened 2017-07-30 16:36 UTC
With `--optimize-minimize`, `libraryName` (and maybe other variables) is not defined and messes with the paginator.

**Comment by Nadeflore** [comment] 2017-09-11 20:47
Fixed in commit df900346bdeed7ed9c44ec7c33e5dff78b5ff982

This bug was caused by libraryPage checking the name of his children,
but in minified build, the names are replaced, hence the bug.
Fixed by adding a static method on classes returning the class name, and using it to retrieve the name

**Closed** 2017-10-03 18:55 UTC
Labels: bug
